on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
jobs:
  exes:
    uses: stanhu/indygreg-actions/.github/workflows/rust-exe.yml@a97acc17e6ee32f136fdf8ab491d1f5bade554fa
    with:
      actions_ref: "a97acc17e6ee32f136fdf8ab491d1f5bade554fa"
      bin: rcodesign
      extra_build_args_linux_gnu: '--all-features'
      extra_build_args_macos: '--all-features'
      extra_build_args_windows: '--all-features'
      just_bootstrap: true
      sccache_s3_bucket: apple-platform-rs-sccache
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test-softhsm-signing:
    name: PKCS#11 Test
    uses: ./.github/workflows/pkcs11-sign-apple-exe.yml
    needs: [exes]
